### ISSUE TITLE
Error when there's a space at the end of the address

### ISSUE THREAD

**Issue by svaldesm** [michaelfranzl/woocommerce-shipping-external-fetch#2]
Hi Michael,

There's a very strange error in this. Whenever you send an address that has a space at the end of the string, it gives "Error processing checkout". For example, if the address is "33 W St " it will fail. 
I've disabled every other plugin and definitely is this one which is causing it. 

Do you know how we can solve this?

Thanks!

**Comment by michaelfranzl** [comment]
What do you mean by "fail"? What's the symptom?

Might be a problem with `json_decode()`. You could look at the return value of `json_last_error()`.

But if JSON decoding fails, the plugin falls back to the shipping fallback cost, and it shouldn't "fail".

As a quick fix, if it's indeed regular spaces (but I doubt that), you could trim them.

**Comment by svaldesm** [comment]
Hi Michael,

Thanks for the quick reply. You can check it here:
http://woocommerce-143029-413850.cloudwaysapps.com

That's a copy on staging of our site.
You can try to add any product to your cart, try to buy it and in the
address (Dirección) field, just add whatever but ending with a space or
"South West 33 " and you will see the error.

It happens independently of the method of payment and any other variable.

I was able to locate where the error triggers, it's
class-wc-frontend-scripts.php line 496 ('i18n_checkout_error'). It's the
only error with that text.

I'm not sure the address is being sent after looking at the code, is it?

Thanks!

**Comment by michaelfranzl** [comment]
It always says "no methods found" (as far as I understand Spanish), no matter what I enter. No errors visible. Could not reproduce the issue on my own webshop - Spaces in the address field work.

**Comment by svaldesm** [comment]
Hi Michael,

The error is still going on. I'm not sure where you tested it (maybe it was the cart), but I'm getting the same error over and over.
Here's a video for you to check what I'm talking about: https://www.useloom.com/share/c213a0c1b1b347059519952c057fa563

In this video, I'm at my checkout. I try first with a space on the address (which gives error) and then without it. It works fine and takes me to the payment gateway.

As I told you, I tried disabling every other plugin except yours and Woocommerce, and this is the one giving errors. Given the error, not sure if language has something to do with it, but in the address that I type there there are no special characters (like á é í that we use here)

**Comment by svaldesm** [comment]
Hi Michael, were you able to reproduce the error?
